// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlNhiLGmW_kgVYQEYZ8KDI0k9t551pP34',
    appId: '1:824515157247:web:e5917ff217cf1cd02300ca',
    messagingSenderId: '824515157247',
    databaseURL: "https://mandalaarenaapp-95d0d-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: 'mandalaarenaapp-95d0d',
    authDomain: 'mandalaarenaapp-95d0d.firebaseapp.com',
    storageBucket: 'mandalaarenaapp-95d0d.firebasestorage.app',
    measurementId: 'G-PLDEDBNW67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_wSmnX20pnoOijQL90oeMasCfCxfdcL0',
    appId: '1:824515157247:android:c29a516d42f1a1482300ca',
    messagingSenderId: '824515157247',
    projectId: 'mandalaarenaapp-95d0d',
    storageBucket: 'mandalaarenaapp-95d0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FlptADwblH7rLcG90FoGYLMUX5R_YCU',
    appId: '1:824515157247:ios:1c496136864fc06b2300ca',
    messagingSenderId: '824515157247',
    projectId: 'mandalaarenaapp-95d0d',
    storageBucket: 'mandalaarenaapp-95d0d.firebasestorage.app',
    iosBundleId: 'com.example.mandalaarenaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5FlptADwblH7rLcG90FoGYLMUX5R_YCU',
    appId: '1:824515157247:ios:1c496136864fc06b2300ca',
    messagingSenderId: '824515157247',
    projectId: 'mandalaarenaapp-95d0d',
    storageBucket: 'mandalaarenaapp-95d0d.firebasestorage.app',
    iosBundleId: 'com.example.mandalaarenaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlNhiLGmW_kgVYQEYZ8KDI0k9t551pP34',
    appId: '1:824515157247:web:50d3c9663fd98fef2300ca',
    messagingSenderId: '824515157247',
    projectId: 'mandalaarenaapp-95d0d',
    authDomain: 'mandalaarenaapp-95d0d.firebaseapp.com',
    storageBucket: 'mandalaarenaapp-95d0d.firebasestorage.app',
    measurementId: 'G-T5NLYQMB0L',
  );
}
